report/csv_export/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products, only: [:index] do
    collection do
      get :export_csv
    end
  end
end

report/csv_export/app/models/concerns/csv_exportable.rb
require 'csv'

module CsvExportable
  extend ActiveSupport::Concern

  module ClassMethods
    def to_csv(header: column_names, columns: column_names, row_sep: "\r\n", encoding: Encoding::CP932)
      records = CSV.generate(row_sep: row_sep) do |csv|
        csv << header
        all.each { |record| csv << record.attributes.values_at(*columns) }
      end
      records.encode(encoding, invalid: :replace, undef: :replace)
    end
  end
end

report/csv_export/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  code          :string(10)       not null              # 商品コード
#  name          :string(50)       not null              # 商品名
#  name_kana     :string(50)       default(""), not null # 商品名カナ
#  price         :integer          not null              # 商品価格
#  purchase_cost :integer          not null              # 仕入原価
#  availability  :boolean          not null              # 販売可能フラグ
#  created_at    :datetime
#  updated_at    :datetime
#

class Product < ActiveRecord::Base
  include CsvExportable
end

report/csv_export/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

report/csv_export/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def export_csv
    @products = Product.all
    send_data @products.to_csv, filename: "#{Time.current.strftime('%Y%m%d')}.csv"
  end
end

report/csv_export/app/helpers/application_helper.rb
module ApplicationHelper
end

report/csv_export/app/helpers/simple_search_form_helper.rb
module SimpleSearchFormHelper
end

report/csv_export/app/helpers/tops_helper.rb
module TopsHelper
end

report/csv_export/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FormExample" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="">Railsアプリケーション構築ガイド</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <%= render 'shared/topnav_link' %>
            </ul>
          </div>
      </div>
    </div>

    <div class="container">
      <% if content_for?(:title) %><h1><%= yield :title %></h1><% end %>
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <hr />

      <footer>
        <p>&copy; Railsアプリケーション構築ガイド 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

report/csv_export/app/views/products/index.html.erb
<% content_for(:title) do %>
  商品CSV出力
<% end %>

<%= link_to 'CSV出力', export_csv_products_path, class: 'btn btn-default' %>

report/csv_export/app/views/shared/_search_box.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-search"></i> 検索条件</h3>
  </div>
  <div class="panel-body">
    <%= yield %>
  </div>
</div>

report/csv_export/app/views/shared/_search_result_box.html.erb
<h1>検索結果</h1>
<%= yield %>