upload/carrierwave_file/config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products

end

upload/carrierwave_file/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  # Validations
  validates :name, presence: true, length: { maximum: 255 }
  validates :image, presence: true
end

upload/carrierwave_file/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

upload/carrierwave_file/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :image, :image_cache, :remove_image)
  end
end

upload/carrierwave_file/app/helpers/application_helper.rb
module ApplicationHelper
  def navlink(title, path, current_controller, current_action)
    css_klass = ""
    if params[:controller] == current_controller.to_s && current_action.include?(params[:action].to_sym)
      css_klass = "active"
    end
    content_tag :li, class: css_klass do
      link_to title, path
    end
  end
end

upload/carrierwave_file/app/views/products/_form.html.erb
<div class="panel panel-default">
<div class="panel-body">
<div class="row">
<div class="col-sm-12">

<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="form-group">
      <label class="control-label">商品名</label>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="control-label">商品画像</label>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <% if f.object.image.present? %>
    <div>
      <label class="control-label">
      選択済の画像削除
      </label><br>
      <label class="control-label">
        <%= f.check_box :remove_image %>
        <%= f.object.image.identifier || f.object.image_identifier %>
      </label>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

</div>
</div>
</div>
</div>

upload/carrierwave_file/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

upload/carrierwave_file/app/views/products/index.html.erb
<h1>Listing products</h1>

<table class="table table-list">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

upload/carrierwave_file/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

upload/carrierwave_file/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Image:</strong>
  <% if @product.image.present? %>
    <%= image_tag @product.image_url %>
  <% end %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>