form/many_to_many_checkbox_forms/config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products do
    collection do
      get :search
    end
  end
end

form/many_to_many_checkbox_forms/app/models/category.rb
# == Schema Information
#
# Table name: categories # カテゴリ
#
#  id         :integer          not null, primary key
#  name       :string(50)       not null              # カテゴリ名
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories
end

form/many_to_many_checkbox_forms/app/models/form/product.rb
# == Schema Information
#
# Table name: products # 商品
#
#  id            :integer          not null, primary key
#  code          :string(10)       not null              # 商品コード
#  name          :string(50)       not null              # 商品名
#  name_kana     :string(50)       default(""), not null # 商品名カナ
#  price         :integer          not null              # 商品価格
#  purchase_cost :integer          not null              # 仕入原価
#  availability  :boolean          not null              # 販売可能フラグ
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Form::Product < Product
  REGISTRABLE_ATTRIBUTES = %i(
    code name name_kana price purchase_cost availability
  )
  REGISTRABLE_RELATIONS = [category_ids: []]

  def selectable_categories
    Category.all
  end
end

form/many_to_many_checkbox_forms/app/models/product.rb
# == Schema Information
#
# Table name: products # 商品
#
#  id            :integer          not null, primary key
#  code          :string(10)       not null              # 商品コード
#  name          :string(50)       not null              # 商品名
#  name_kana     :string(50)       default(""), not null # 商品名カナ
#  price         :integer          not null              # 商品価格
#  purchase_cost :integer          not null              # 仕入原価
#  availability  :boolean          not null              # 販売可能フラグ
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Product < ActiveRecord::Base
  has_many :product_categories
  has_many :categories, through: :product_categories
  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates :code, presence: true, length: { maximum: 10 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :name_kana, kana: true, length: { maximum: 50 }
  validates :price,
             presence: true,
             numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :purchase_cost,
             presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :availability, inclusion: { in: [true, false] }
end

form/many_to_many_checkbox_forms/app/models/product_category.rb
# == Schema Information
#
# Table name: product_categories # 商品カテゴリ
#
#  id          :integer          not null, primary key
#  product_id  :integer          not null              # 商品ID
#  category_id :integer          not null              # カテゴリID
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

form/many_to_many_checkbox_forms/app/models/validators/kana_validator.rb
class KanaValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([ァ-ヴーA-Za-z0-9\s]+)\z/
      record.errors[attribute] << (options[:message] || "はカタカナで入力してください")
    end
  end
end

form/many_to_many_checkbox_forms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

form/many_to_many_checkbox_forms/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @q = Product.search
  end

  def search
    @q = Product.search(search_params)
    @products = @q
      .result
      .order(availability: :desc, code: :asc)
      .decorate
  end

  def new
    @product = Form::Product.new
  end

  def edit
    @product = Form::Product.find(params[:id])
  end

  def create
    @product = Form::Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "商品 #{@product.name} を登録しました。"
    else
      render :new
    end
  end

  def update
    @product = Form::Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path, notice: "商品 #{@product.name} を更新しました。"
    else
      render :edit
    end
  end

  private

  def search_params
    search_conditions = %i(
      code_cont name_cont name_kana_cont availability_true
      price_gteq price_lteq purchase_cost_gteq purchase_cost_lteq
    )
    params.require(:q).permit(search_conditions)
  end

  def product_params
    params
      .require(:form_product)
      .reverse_merge(category_ids: [])
      .permit(Form::Product::REGISTRABLE_ATTRIBUTES + Form::Product::REGISTRABLE_RELATIONS)
  end
end

form/many_to_many_checkbox_forms/app/helpers/application_helper.rb
module ApplicationHelper
  def navlink(title, path, current_controller, current_action)
    css_klass = ""
    if params[:controller] == current_controller.to_s && current_action.include?(params[:action].to_sym)
      css_klass = "active"
    end
    content_tag :li, class: css_klass do
      link_to title, path
    end
  end
end

form/many_to_many_checkbox_forms/app/helpers/orders_helper.rb
module OrdersHelper
end

form/many_to_many_checkbox_forms/app/helpers/simple_search_form_helper.rb
module SimpleSearchFormHelper
end

form/many_to_many_checkbox_forms/app/helpers/tops_helper.rb
module TopsHelper
end

form/many_to_many_checkbox_forms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FormExample" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="">Railsアプリケーション構築ガイド</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <%= render 'shared/topnav_link' %>
            </ul>
          </div>
      </div>
    </div>

    <div class="container">
      <% if content_for?(:title) %><h1><%= yield :title %></h1><% end %>
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <hr />

      <footer>
        <p>&copy; Railsアプリケーション構築ガイド 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

form/many_to_many_checkbox_forms/app/views/products/_form.html.erb
<div class="panel panel-default">
<div class="panel-body">
<div class="row">
<div class="col-sm-12">

<%= form_for(@product, url: path, method: method) do |f| %>
  <div class="col-sm-6">
  <div class="form-group">
    <label class="control-label" for="">商品コード</label>
    <%= f.text_field :code, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label" for="">商品名</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label" for="">商品名カナ</label>
    <%= f.text_field :name_kana, class: 'form-control' %>
  </div>
  </div>

  <div class="col-sm-6">
  <div class="form-group">
    <label class="control-label" for="">商品価格</label>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label class="control-label" for="">仕入原価</label>
    <%= f.text_field :purchase_cost, class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
    <div class="checkbox">
      <label>
        <%= f.check_box :availability, {}, 'true', 'false' %>
        販売可否
      </label>
    </div>
    </div>
  </div>
  </div>

  <div class="col-sm-12">
    <div class="form-group">
      <label class="control-label" for="">商品カテゴリ</label>
      <div class="checkbox form-inline">
      <% f.object.selectable_categories.each do |category| %>
        <%= f.label :category_ids, value: category.id, class: 'checkbox' do %>
          <%= f.check_box :category_ids, { multiple: true }, category.id, nil %>
          <%= category.name %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-12">
  <div class="text-center">
  <%= f.submit '登録', class: 'btn btn-primary' %>
  </div>
  </div>
<% end %>

</div><!-- /col-sm-12 -->
</div><!-- /row -->
</div><!-- /panel-body -->
</div><!-- /panel -->

form/many_to_many_checkbox_forms/app/views/products/_search_form.html.erb
<%= render layout: 'shared/search_box' do %>

<div class="row">
<div class="col-sm-6">
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">商品コード</label>
    <div class="col-sm-8">
      <%= f.text_field :code_cont, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">商品名</label>
    <div class="col-sm-8">
      <%= f.text_field :name_cont, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">商品名カナ</label>
    <div class="col-sm-8">
      <%= f.text_field :name_kana_cont, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for=""></label>
    <div class="col-sm-6">
      <div class="checkbox">
        <label>
          <%= f.check_box :availability_true %>
          販売中のみ
        </label>
      </div>
    </div>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最低商品価格</label>
    <div class="col-sm-8">
      <%= f.text_field :price_gteq, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最高商品価格</label>
    <div class="col-sm-8">
      <%= f.text_field :price_lteq, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最低仕入原価</label>
    <div class="col-sm-8">
      <%= f.text_field :purchase_cost_gteq, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-4 control-label" for="">最高仕入原価</label>
    <div class="col-sm-8">
      <%= f.text_field :purchase_cost_lteq, class: 'form-control' %>
    </div>
  </div>
</div>

<div class="col-sm-12 row text-center">
  <%= link_to products_path, class: 'btn btn-default btn-left' do %>クリア<% end %>
  <button class="btn btn-default btn-primary" type="submit"><i class="fa fa-search"></i> 検索</button>
</div>

</div>

<% end %>

form/many_to_many_checkbox_forms/app/views/products/edit.html.erb
<% content_for(:title) do %>
  商品更新
<% end %>

<%= render 'form', path: product_path(@product), method: :put %>

form/many_to_many_checkbox_forms/app/views/products/index.html.erb
<% content_for(:title) do %>
  商品検索
<% end %>

<%= search_form_for(@q, url: search_products_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

form/many_to_many_checkbox_forms/app/views/products/new.html.erb
<% content_for(:title) do %>
  商品登録
<% end %>

<%= render 'form', path: products_path, method: :post %>

form/many_to_many_checkbox_forms/app/views/products/search.html.erb
<% content_for(:title) do %>
  商品検索
<% end %>

<%= search_form_for(@q, url: search_products_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= render 'search_form', f: f %>
<% end %>

<%= render layout: 'shared/search_result_box' do %>
  <table class="table table-list ">
  <thead>
    <tr>
      <th>販売状況</th>
      <th>商品コード</th>
      <th>商品名</th>
      <th>販売価格</th>
      <th>仕入原価</th>
      <th></th>
    </tr>
  </thead>
  <% @products.each do |product| %>
  <tbody>
  <tr>
    <td><%= product.sales_condition %> </td>
    <td><%= product.code %></td>
    <td><%= product.name %></td>
    <td><%= product.display_price %></td>
    <td><%= product.display_purchase_cost %></td>
    <td><%= link_to '編集', edit_product_path(product), class: 'btn btn-default' %></td>
  </tr>
  </tbody>
<% end %>
</table>
<% end %>